---
title: "workflow01"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{workflow01}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(incidenceflow)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(aweek)
library(janitor)
# library(avallecam)
library(compareGroups)
library(incidence)
library(patchwork)
# library(avallecam)
library(EpiEstim)
library(colorspace)
theme_set(theme_bw())
```

```{r,eval=FALSE}
# example outbreak --------------------------------------------------------

library(outbreaks) #sample data
library(incidence) #core functions
# library(avallecam) #improvements
outbreak_data <- ebola_sim$linelist$date_of_onset
```

```{r}
# packages ----------------------------------------------------------------

if(!require("devtools")) install.packages("devtools")
# if(!require("avallecam")) devtools::install_github("avallecam/avallecam") #improvements

library(tidyverse) #magrittr and purrr packages
library(lubridate) #ymd
library(outbreaks) #sample data
library(incidence) #core functions

# example outbreak --------------------------------------------------------

dat <- ebola_sim$linelist$date_of_onset
i.7 <- incidence(dat, interval=7)
# plot(i.7)
f1 <- fit(i.7[1:20])
f2 <- fit_optim_split(i.7)

# broom like functions ----------------------------------------------------

# tidy
f1 %>% tidy_incidence()
f2 %>% pluck("fit") %>% tidy_incidence()

# glance
f1 %>% glance_incidence()
f2 %>% pluck("fit") %>% glance_incidence()


# using purrr -------------------------------------------------------------

# using purrr::map family function allows easy stratification
# for gender and could be extrapolated to administrative levels
# in country level analysis

incidence_purrr <- ebola_sim$linelist %>% 
  as_tibble() %>% 
  #filter observations explicitly before incidence()
  filter(date_of_onset<lubridate::ymd(20141007)) %>% 
  #stratify by any group of covariates
  group_by(gender) %>% 
  nest() %>% 
  mutate(incidence_strata=map(.x = data,
                              .f = ~incidence(.x %>% pull(date_of_onset),
                                              interval=7))) %>% 
  mutate(strata_fit=map(.x = incidence_strata,
                            .f = fit)) %>% 
  mutate(strata_fit_tidy=map(.x = strata_fit,
                                  .f = tidy_incidence)) %>% 
  mutate(strata_fit_glance=map(.x = strata_fit,
                                       .f = glance_incidence))

# keep only the tibbles
incidence_purrr_tibble <- incidence_purrr %>% 
  select(-data,-incidence_strata,-strata_fit)

# tidy_incidence output
incidence_purrr_tibble %>% 
  unnest(cols = c(strata_fit_tidy))

# glance_incidence output
incidence_purrr_tibble %>% 
  unnest(cols = c(strata_fit_glance))
```


```{r, eval=FALSE}
#### execute -------------------------------

# vigilancia_covid19
nest_dynamics <- vigilancia_covid19 %>% 
  mutate(nm_depa=if_else(nm_prov=="lima","lima_metropolitana",nm_depa)) %>% 
  # filter(magrittr::is_in(nm_dist,c("chimbote","huacho","huaraz"))) %>% 
  # filter(magrittr::is_in(nm_prov,c("lima"))) %>% 
  # clean
  incidence_nest_clean(
    nest_level = cd_dist,
    custom_pre_cleaning = covid_pre_cleaning,
    issue_number = 40) %>% 
  # join a ubigeo dictionary
  left_join(ubigeo_diccionario) %>% 
  # create date
  mutate(data_dates=map(
    .x = data,
    .f = incidence_dates_mutate,
    variable_date = fecha_de_inicio_de_sintomas_corregido)) %>% 
  unnest(cols = c(data_dates)) %>% 
  # set incidence v1
  mutate(i_daily_to_lastone = pmap(
    .l = select(., data = data, last_date = date_lastone),
    .f = possibly(incidence_pull,NA_real_),
    variable_date = fecha_de_inicio_de_sintomas_corregido,
    interval=7)) %>% 
  # set incidence v2
  mutate(i_daily_to_delay = pmap(
    .l = select(., data = data, last_date = date_lastlag_weeks),
    .f = possibly(incidence_pull,NA_real_),
    variable_date = fecha_de_inicio_de_sintomas_corregido,
    interval=7)) %>%
  # set incidence v3
  mutate(i_daily_to_lastone_d = pmap(
    .l = select(., data = data, last_date = date_lastone),
    .f = possibly(incidence_pull,NA_real_),
    variable_date = fecha_de_inicio_de_sintomas_corregido,
    interval=1)) %>% 
  # set incidence v4
  mutate(i_daily_to_delay_d = pmap(
    .l = select(., data = data, last_date = date_lastlag_weeks),
    .f = possibly(incidence_pull,NA_real_),
    variable_date = fecha_de_inicio_de_sintomas_corregido,
    interval=1)) %>% 
  # fit incidence
  mutate(incidence_fit=map(.x = i_daily_to_delay,
                           .f = possibly(incidence::fit,NA_real_),
                           quiet = T)) %>% 
  # fit incidence split
  mutate(incidence_split=map(.x = i_daily_to_delay,
                           .f = possibly(incidence::fit_optim_split,
                                         list(split=lubridate::ymd(00000000))),
                           quiet = T)) %>% 
  mutate(incidence_split_fit=map(.x = incidence_split,.f = pluck("fit"))) %>% 
  
  # extract real peak
  mutate(date_split_peak=map(.x = incidence_split,.f = pluck("split"))) %>% 
  unnest(cols = c(date_split_peak)) %>% 
  mutate(incidence_split_real=if_else(is.na(date_split_peak),"n","y")) %>%
  
  # tidy + glance for fit and incidence
  mutate(incidence_tidy=map(.x = incidence_fit,
                            .f = possibly(tidy_incidence,tibble()))) %>% 
  mutate(incidence_glance=map(.x = incidence_fit,
                              .f = possibly(glance_incidence,tibble()))) %>% 
  mutate(incidence_split_tidy=map(.x = incidence_split_fit,
                            .f = possibly(tidy_incidence,tibble()))) %>% 
  mutate(incidence_split_glance=map(.x = incidence_split_fit,
                              .f = possibly(glance_incidence,tibble()))) %>% 
  
  # unify tidy and glance
  mutate(one_incidence_fit=if_else(incidence_split_real=="y",
                                   incidence_split_fit,incidence_fit)) %>% 
  mutate(one_incidence_tidy=if_else(incidence_split_real=="y",
                                    incidence_split_tidy,incidence_tidy)) %>% 
  mutate(one_incidence_glance=if_else(incidence_split_real=="y",
                                      incidence_split_glance,incidence_glance)) %>% 
  # select relevant results
  select(cd_dist,
         data,
         n_pre_clean, n_pos_clean,
         i_daily_to_lastone,i_daily_to_lastone_d,
         i_daily_to_delay,i_daily_to_delay_d,
         starts_with("one_"),
         date_split_peak,date_firstone,date_lastlag_weeks,
         starts_with("cd_"),starts_with("nm_")) %>%
  
  # output 01: create incidence + fit figure
  mutate(incidence_fit_figure=pmap(
    .l = select(.,data = i_daily_to_lastone,
                fit = one_incidence_fit,
                date_start = date_firstone,
                date_end = date_lastlag_weeks,
                nombre_area = cd_dist),
    .f = possibly(dynamic_output_figure,NA_real_),
    date_breaks = "7 day")) %>% 
  
  # output 02: create incidence only figure
  mutate(incidence_only_figure=pmap(
    .l = select(.,data = i_daily_to_lastone_d,
                # fit = one_incidence_fit,
                date_start = date_firstone,
                date_end = date_lastlag_weeks,
                nombre_area = cd_dist),
    .f = possibly(incidence_output_figure,NA_real_),
    date_breaks = "7 day")) %>% 

  # estimate effect reproductive number
  mutate(incidente_rt = map(
    .x = i_daily_to_delay_d,
    .f = ~estimate_R(incid = .x,
                     method = "parametric_si",
                     config = make_config(list(mean_si = 3.96,std_si = 4.75))))) %>% 
  # return rt time serie
  mutate(tsibble_rt=map(.x = incidente_rt,.f = epiestim_tibble_rt)) %>% 
  mutate(current_rt=map(.x = tsibble_rt,.f = epiestim_current_rt)) %>% 
  mutate(rt_figure=map(.x = tsibble_rt,.f = figure_tsibble_rt)) %>% 
  
  select(-starts_with("i_"),-one_incidence_fit,-incidente_rt,#-tsibble_rt,
         date_lastlag_weeks)
```

```{r,eval=FALSE}
#### nested figures -------------------------------
department_transmission <- nest_dynamics %>% 
  mutate(nm_depa_nest=nm_depa) %>% 
  group_by(nm_depa) %>% 
  nest() %>% 
  ungroup() %>% 
  mutate(fig01=map(data,nested_figure_01)) %>% 
  mutate(fig02=map(data,nested_figure_02)) %>% 
  mutate(fig03=map(data,nested_figure_03)) %>%
  mutate(fig04=map(data,nested_figure_04)) %>%
  mutate(tab01=map(data,nested_table_01)) %>% 
  mutate(tab02=map(data,nested_table_02)) %>% 
  mutate(tab03=map(data,nested_table_03))
```

```{r,eval=FALSE}
region_name <- "lima_metropolitana"

department_transmission %>% 
  filter(nm_depa==region_name) %>% 
  pull(fig01) %>% pluck(1)
department_transmission %>% 
  filter(nm_depa==region_name) %>% 
  pull(fig02) %>% pluck(1)
department_transmission %>% 
  filter(nm_depa==region_name) %>% 
  pull(fig03) %>% pluck(1)
department_transmission %>% 
  filter(nm_depa==region_name) %>% 
  pull(fig04) %>% pluck(1)

department_transmission %>% 
  filter(nm_depa==region_name) %>% 
  pull(tab01) %>% pluck(1)
department_transmission %>% 
  filter(nm_depa==region_name) %>% 
  pull(tab02) %>% pluck(1)
department_transmission %>% 
  filter(nm_depa==region_name) %>% 
  pull(tab03) %>% pluck(1)
```

```{r,eval=FALSE}
nest_dynamics %>%
  slice(1) %>%
  pull(incidence_fit_figure) %>%
  pluck(1)
nest_dynamics %>%
  slice(1) %>%
  pull(incidence_only_figure) %>%
  pluck(1)
nest_dynamics %>%
  slice(1) %>%
  pull(rt_figure) %>%
  pluck(1)
```

